version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=gnc
            - POSTGRES_PASSWORD=gnc
            - POSTGRES_DB=gnucash
        # persist the postgres data to disk so we don't lose it
        # on rebuilds.
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - '5432:5432'
